spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.1.108:3306/blog_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: sz555555
      stat-view-servlet:
        login-username: admin
        login-password: admin
